#:schema node_modules/wrangler/config-schema.json
name = "hn-clone-frontend"
main = ".next/server.js"
site.bucket = ".next"
build.command = "npm run build"

[vars]
NEXT_PUBLIC_API_URL = "https://hn-clone-api.hacker-news-roo.workers.dev"

[env.production]
vars = { NEXT_PUBLIC_API_URL = "https://hn-clone-api.hacker-news-roo.workers.dev" }