name = "hn-clone-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# D1 Database configuration
# Create a database with: `wrangler d1 create hn-clone-db`
# Then update the database_id with your actual database ID
[[ d1_databases ]]
binding = "DB" # Available in your worker on env.DB
database_name = "hn-clone-db"
database_id = "78adfc48-0926-48c5-91d6-9f85b876a5d2" # Actual database ID
migrations_dir = "drizzle"

# Environment variables
# In production, set these in the Cloudflare dashboard
[vars]
# JWT secret - MUST be changed in production
# Generate a strong secret with: `openssl rand -base64 32`
JWT_SECRET = "mfVxIxhVrW0tuU2XUaxLH4jEpPYg5DgW7Uo8aIYQ4GA=" # For testing only, must be set in Cloudflare dashboard for production